import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script"; 
import { MovieProvider } from "@/context/MovieContext"; 
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Movie Ticket",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
       <MovieProvider> 
          {children}
          <ToastContainer theme="dark" position="top-center" />
        </MovieProvider>
        
        {/* Razorpay SDK Loader - Ye hona bahut zaroori hai */}
        <Script 
          src="https://checkout.razorpay.com/v1/checkout.js" 
          strategy="beforeInteractive" 
        />
      </body>
    </html>
  );
}